channels:
    - anaconda
    - pytorch
dependencies:
    - python==3.7
    - numpy==1.19.1
    - pandas==1.1.3
    - scikit-learn==0.23.2
    - bs4==4.9.3
    - matplotlib==3.3.1
    - wordcloud==1.8.1
    - nltk==3.5
    - pytorch==1.7.0 
    - torchvision==0.8.1 
    - torchaudio==0.7.0 
    - cudatoolkit=10.2
    - transformers==3.5.1
    - pip
    - pip:
        - tweet-preprocessor==0.6.0